### ISSUE TITLE
Want to add footer in this same as amazon 

### ISSUE THREAD

**Issue by Aastik-Mehta-22** [TANISHQGOYAL07/amazon_clone#1]
I'm proposing to add a footer section to enhance the user experience by providing essential information and quick links at the bottom of each page. The footer will include:

Company Information: Links to "About Us," "Careers," and "Press Releases."
Customer Support: Quick links to "Help," "Contact Us," and "Returns & Orders."
Social Media Links: Icons for popular social media platforms for users to stay connected.
Terms and Policies: Links for "Privacy Policy," "Terms of Service," and "Cookie Preferences."
This addition will improve site navigation and user accessibility, giving the clone a more polished, real-world look. Let me know if you have specific styling guidelines or additional items you'd like in the footer!

**Comment by Aastik-Mehta-22** [comment]
@TANISHQGOYAL07  kindly assign issue to me bro i knew you are from my campus

**Comment by TANISHQGOYAL07** [comment]
@Aastik-Mehta-22  ya ya offcourse bro go with it even i feel its necessary
